introduce bundle subcommand
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

diff --git a/srpmix7 b/srpmix7
--- a/srpmix7
+++ b/srpmix7
@@ -24,6 +24,7 @@ readonly prefix=srpmix7
 readonly PREFIX=${(U)prefix}
 readonly SELF=$0:t
 readonly c_version=7.0.0
+readonly UCTAGS=${UCTAGS:-~/bin/u-ctags}
 
 #
 # TODO
@@ -34,8 +35,9 @@ readonly c_version=7.0.0
 #
 # Namespace
 #
-# d_: deploy related
+# b_: bundle
 # c_: constant value in files in "raw directory"
+# d_: deploy related
 # i_: internal subcommand
 # p_: file/directory names of lower directory structure
 # P_: file/directory names of upper directory structure
@@ -57,11 +59,19 @@ readonly -x p_uname_version=$p_uname/version
 readonly -x p_log=_log
 readonly -x p_stmp=__src_tmp
 readonly -x p_xtmp=__expander_tmp
+readonly -x p_bundle_status=_status
+readonly -x p_bundle_log=_log
+readonly -x p_bundle_uname=_uname
+
+readonly -x p_srpm_spec=srpm.spec
 
 readonly -x s_unknown=unknown
 readonly -x s_successful=successful
 readonly -x s_bug=BUG
 readonly -x s_incomplete=incomplete
+
+readonly -x s_bundle_unknown=unknown
+readonly -x s_bundle_successful=successful
 
 readonly -x p_unknown=${(U)${s_unknown}}
 readonly -x p_successful=${(U)${s_successful}}
@@ -116,6 +126,10 @@ EVAR[TMPDIR]="Directory where temorary directories are created"
 
 typeset -A REQUIREMENTS
 REQUIREMENTS=(
+)
+
+typeset -A BUNDLES
+BUNDLES=(
 )
 
 #
@@ -471,6 +485,361 @@ i_null_run()
 {
     echo i_null_run
 }
+
+#
+#
+# Subcommand: bundle
+#
+#
+ICMD+=bundle
+ICMD_DESC[bundle]="make and manage bundles"
+
+i_bundle_help()
+{
+    local k
+
+    echo "$SELF bunlde [OPTIONS] SRPMIX7DIR BUNDLE [BUNDLE_ARGS...]"
+    echo
+
+    echo "OPTIONS:"
+    echo
+    {
+	echo "	--action-when-error=abort|continue*"
+	echo "	--debug"
+	echo "	--quit-after=optparse|prepare"
+	echo "	--trace"
+	echo "	--update"
+    }
+
+    echo
+
+    echo "BUNDLE:"
+    echo
+    for k in ${(k)BUNDLES}; do
+	=printf "%-10s	%s\n" "$k" "${BUNDLES[$k]}" | indent
+    done
+    echo
+
+}
+
+typeset -A BUNDLE_VERSION
+
+uctags_desc="%s for %s generated by universal ctags default option"
+BUNDLES[uctags_tags_pre_build]=$(printf "${uctags_desc}" tags pre_build)
+BUNDLE_VERSION[uctags_tags_pre_build]="0.0.0"
+REQUIREMENTS[bundle_uctags_tags_pre_build]="${UCTAGS}"
+
+BUNDLES[uctags_tags_srpm_spec]=$(printf "${uctags_desc}" tags srpm.spec)
+BUNDLE_VERSION[uctags_tags_srpm_spec]="0.0.0"
+REQUIREMENTS[bundle_uctags_tags_srpm_spec]="${UCTAGS}"
+
+BUNDLES[uctags_tags_archives]=$(printf "${uctags_desc}" tags archives)
+BUNDLE_VERSION[uctags_tags_archives]="0.0.0"
+REQUIREMENTS[bundle_uctags_tags_archives]="${UCTAGS}"
+
+BUNDLES[uctags_TAGS_pre_build]=$(printf "${uctags_desc}" TAGS pre_build)
+BUNDLE_VERSION[uctags_TAGS_pre_build]="0.0.0"
+REQUIREMENTS[bundle_uctags_TAGS_pre_build]="${UCTAGS}"
+
+BUNDLES[uctags_TAGS_srpm_spec]=$(printf "${uctags_desc}" TAGS srpm.spec)
+BUNDLE_VERSION[uctags_TAGS_srpm_spec]="0.0.0"
+REQUIREMENTS[bundle_uctags_TAGS_srpm_spec]="${UCTAGS}"
+
+BUNDLES[uctags_TAGS_archives]=$(printf "${uctags_desc}" TAGS archives)
+BUNDLE_VERSION[uctags_TAGS_archives]="0.0.0"
+REQUIREMENTS[bundle_uctags_TAGS_archives]="${UCTAGS}"
+
+
+b_run_uctags_tags_pre_build()
+{
+    b_run_uctags_tags_common ${p_pre_build} "$@"
+}
+
+b_run_uctags_tags_srpm_spec()
+{
+    b_run_uctags_tags_common ${p_srpm_spec} "$@"
+}
+
+b_run_uctags_tags_archives()
+{
+    b_run_uctags_tags_common ${p_archives} "$@"
+}
+
+b_run_uctags_TAGS_pre_build()
+{
+    b_run_uctags_tags_common ${p_pre_build} "$@"  -e
+}
+
+b_run_uctags_TAGS_srpm_spec()
+{
+    b_run_uctags_tags_common ${p_srpm_spec} "$@" -e
+}
+
+b_run_uctags_TAGS_archives()
+{
+    b_run_uctags_tags_common ${p_archives} "$@" -e
+}
+
+b_run_uctags_tags_common()
+{
+    local subtarget=$1
+    shift
+
+    if [[ "$1" == --update ]]; then
+	shift
+    fi
+
+    local d=$1
+    local t=$2
+    shift 2
+
+    local o
+    local flag
+    local suffix
+
+    if member -e "$@"; then
+	suffix=TAGS
+    else
+	suffix=tags
+    fi
+
+    o=$t/${subtarget}.${suffix}
+    if [[ -e "$d/${subtarget}" ]]; then
+	if [[ -d "${d}/${subtarget}" ]]; then
+	    flag=-R
+	fi
+
+	${UCTAGS} -o $o ${flag} "$@" $d/${subtarget} || throw Ctags
+	sed -i -e "s|$d|../..|" $o || throw Sed
+    else
+	return 1
+    fi
+    return 0
+}
+
+i_bundle_run()
+{
+    local c=${${0#i_}%_run}
+    local opt
+    local next
+    local action_when_error=continue
+
+    local b
+    local d
+    local -a args
+    local s
+    local r
+
+    local update
+    local debug
+    local quit_after
+
+    while true; do
+	case $1 in
+	    (--help|-h)
+		i_${c}_help
+		return 0
+		;;
+	    (--[^=]#=*)
+		opt=${1%%=*}
+		next=${1#*=}
+		shift 1
+		1=( "$opt" "$next" "$@" )
+		;;
+	    (--update)
+		update=--update
+		shift 1
+		;;
+	    (--quit-after)
+		opt=$1
+		if [[ -z "$2" ]]; then
+		    -E- "$c: value for $opt is not given"
+		else
+		    case "$2" in
+			(optparse|prepare) quit_after="--quit-after=$2" ;;
+			(*) -E- "$c: unexpected value for $opt" ;;
+		    esac
+		fi
+		shift 2
+		;;
+	    (--action-when-error)
+		if [[ -z "$2" ]]; then
+		    -E- "$c: value for $1 is not given"
+		else
+		    case $2 in
+			(abort|continue) action_when_error="$2";;
+			(*) -E- "$c: unexpected value for $1: $2";;
+		    esac
+		fi
+		shift 2
+		;;
+	    (--debug)
+		debug=yes
+		shift
+		;;
+	    (--trace|-x)
+		set -x
+		shift
+		;;
+	    (-*|--*)
+		-E- "$c: unknown option: $1"
+		;;
+	    (*)
+		break
+		;;
+	esac
+    done
+
+
+    d=$1
+    if [[ -z "$d" ]]; then
+	-E- "$c: no target directory given"
+    elif [[ ! -e "$d" ]]; then
+	-E- "$c: no such dentry: $d"
+    elif [[ ! -d "$d" ]]; then
+	-E- "$c: not a directory: $d"
+    else
+	shift 1
+    fi
+
+    if [[ ! -e $d/${p_bundles} ]]; then
+	-E- "$c: no such dentry: $d/${p_bundles}"
+    elif [[ ! -d $d/${p_bundles} ]]; then
+	-E- "$c: not a directory: $d/${p_bundles}"
+    elif [[ ! -w $d/${p_bundles} ]]; then
+	-E- "$c: not a writable directory: $d/${p_bundles}"
+    fi
+
+    if [[ ! -e "$d/$p_status" ]]; then
+	-E- "$c: no $p_status found in $d"
+    elif [[ ! -r "$d/$p_status" ]]; then
+	-E- "$c: cannot read $d/$p_status"
+    fi
+
+    case $(< $d/$p_status) in
+	(${s_successful})
+	;;
+	(${s_incomplete}*)
+	;;
+	(${s_bug}*)
+	    -E- "$c: don't make bundle for a directory having BUG status" ;;
+	(*)
+	    -E- "$c: don't make bundle for a directory having unknown status" ;;
+    esac
+
+    b=$1
+    if [[ -z "$b" ]]; then
+	-E- "$c: no bundle name given"
+    elif ! member "$b" ${(k)BUNDLES}; then
+	-E- "$c: no such bundle: $b"
+    else
+	shift 1
+    fi
+
+    check_requirements bundle $b
+
+    if [[ "${debug}" == 'yes' ]]; then
+	echo srpmix7dir: $d
+	echo bundle: $b
+    fi
+
+    args=( "$@" )
+
+    if [[ "$quit_after" == "optparse" ]]; then
+	exit 0
+    fi
+
+    if [[ -f ${d}/${p_bundles}/${b}/$p_bundle_status ]]; then
+	if [[ -z "${update}" ]]; then
+	    case $(< ${d}/${p_bundles}/${b}/$p_bundle_status) in
+		($s_bundle_successful)
+		    return 0
+	    esac
+	fi
+    fi
+
+    set +e
+    {
+	local t
+
+	if ! t=$(mktemp --tmpdir --directory ${SELF}-BUNDLE-${b}.XXXXXXXXXX) ; then
+	    throw Creation
+	elif [[ "${debug}" == "yes" ]]; then
+	    echo tmpdir: $t
+	fi
+
+	if ! b_prepare $t; then
+	    throw Preparation
+	else
+	    {
+		: &&
+		    echo "${b}" > $t/$p_bundle_uname/bundle &&
+		    echo ${BUNDLE_VERSION[${b}]} > $t/$p_bundle_uname/b_version &&
+		    echo "${args[@]}" > $t/$p_bundle_uname/b_args
+	    } || throw Preparation
+	fi
+
+	if [[ "$quit_after" == "prepare" ]]; then
+	    exit 0
+	fi
+	b_run_${b} ${update} ${d} ${t} "$args[@]" > $t/$p_bundle_log/b.log 2>&1
+    } always {
+	s=$?
+	if catch 'Preparation'; then
+	    r=1
+	elif catch 'Ctags'; then
+	    cat $t/$p_bundle_log/b.log 1>&2
+	    r=2
+	elif catch '*'; then
+	    cat $t/$p_bundle_log/b.log 1>&2
+	    r=2
+	elif [[ $s != 0 ]]; then
+	    cat $t/$p_bundle_log/b.log 1>&2
+	    r=1
+	else
+	    r=0
+	    if [[ -e "${d}/${p_bundles}/${b}" ]]; then
+		mv "${d}/${p_bundles}/${b}" "${d}/${p_bundles}/.${b}"
+	    fi
+	    mv $t "${d}/${p_bundles}/${b}"
+	    rm -rf "${d}/${p_bundles}/.${b}"
+	    b_commit "${d}/${p_bundles}/${b}" "${s_bundle_successful}"
+	fi
+
+	if [[ -e "$t" && "${debug}" != "yes" ]]; then
+	    rm -rf "$t"
+	fi
+    }
+    set -e
+
+    return $r
+}
+
+b_commit()
+{
+    local d=$1
+    local msg=$2
+    echo "$msg" > $d/.$p_status
+    mv $d/.$p_status $d/$p_status
+}
+
+b_prepare()
+{
+    local d=$1
+    local elt
+
+    for elt in $p_bundle_uname $p_bundle_log; do
+	if ! mkdir ${d}/${elt}; then
+	    return 1
+	fi
+    done
+
+    elt=.$p_status
+    echo "${s_bundle_unknown}" > ${d}/${elt}
+
+    return 0
+}
+
 
 #
 #
@@ -1461,9 +1830,7 @@ i_expand_run()
 	    if [[ "$s" == 0 || "$action_when_error" == continue ]]; then
 		if x_dest_${dtype}_transfer "$t" "$dloc"; then
 		    x_dest_${dtype}_commit "$dloc"
-		    #
-		    # TODO; COMMIT_HOOK
-		    #
+		    attach_bundles $dloc
 		else
 		    delayed_emsg="$c: failed to transfer expanded data to $dtype:$dloc from $t"
 		    r=3
@@ -2150,6 +2517,23 @@ x_expand_lcopy_check()
 {
     :
 }
+
+
+#
+#
+# Bundle
+#
+#
+
+attach_bundles()
+{
+    local d=$1
+    local b
+    for b in ${(k)BUNDLES}; do
+	subcommand_run bundle $d $b || :
+    done
+}
+
 #
 #
 # MAIN
